workflows:
  ios-test-workflow:
    name: Ios Test Workflow
    max_build_duration: 20
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      ios_signing:
        distribution_type: app_store
        bundle_identifier: dev.mikefairhurst.behtterRoasts
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

  simulator-native-ios:
    name: Ios Test Workflow
    max_build_duration: 20
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build .app
        script: |
          flutter build ios --simulator \
            --build-name=1.0.0 \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/**/*.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
