// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZXPqSe2Orj1qWUcBY33i7JNg0JvGjt64',
    appId: '1:476682855230:web:323054333fdc1d383d826f',
    messagingSenderId: '476682855230',
    projectId: 'behmor-roast-app',
    authDomain: 'behmor-roast-app.firebaseapp.com',
    storageBucket: 'behmor-roast-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcj96dEAyduyOMGcjXWzuntDNVfVSO4T4',
    appId: '1:476682855230:android:3df45aa63776f71b3d826f',
    messagingSenderId: '476682855230',
    projectId: 'behmor-roast-app',
    storageBucket: 'behmor-roast-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbWPFzh0LjhkK7ot6GbAjPJWNdqsRS22E',
    appId: '1:476682855230:ios:bb5717a35dcdf0df3d826f',
    messagingSenderId: '476682855230',
    projectId: 'behmor-roast-app',
    storageBucket: 'behmor-roast-app.appspot.com',
    iosBundleId: 'com.example.behmorRoast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbWPFzh0LjhkK7ot6GbAjPJWNdqsRS22E',
    appId: '1:476682855230:ios:bb5717a35dcdf0df3d826f',
    messagingSenderId: '476682855230',
    projectId: 'behmor-roast-app',
    storageBucket: 'behmor-roast-app.appspot.com',
    iosBundleId: 'com.example.behmorRoast',
  );
}
