// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcj96dEAyduyOMGcjXWzuntDNVfVSO4T4',
    appId: '1:476682855230:android:de9408f495d89ff53d826f',
    messagingSenderId: '476682855230',
    projectId: 'behmor-roast-app',
    storageBucket: 'behmor-roast-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbWPFzh0LjhkK7ot6GbAjPJWNdqsRS22E',
    appId: '1:476682855230:ios:d02fea038051e3e53d826f',
    messagingSenderId: '476682855230',
    projectId: 'behmor-roast-app',
    storageBucket: 'behmor-roast-app.appspot.com',
    androidClientId: '476682855230-8sbaq7qdefavptll5i63t5c1okanjq3s.apps.googleusercontent.com',
    iosClientId: '476682855230-povgmevit3agcfchqgthgqafp38igtep.apps.googleusercontent.com',
    iosBundleId: 'dev.mikefairhurst.behtterRoasts',
  );
}
